//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Alabama
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VPSS1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VPSS1Entities object using the connection string found in the 'VPSS1Entities' section of the application configuration file.
        /// </summary>
        public VPSS1Entities() : base("name=VPSS1Entities", "VPSS1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VPSS1Entities object.
        /// </summary>
        public VPSS1Entities(string connectionString) : base(connectionString, "VPSS1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VPSS1Entities object.
        /// </summary>
        public VPSS1Entities(EntityConnection connection) : base(connection, "VPSS1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company_Expanses> Company_Expanses
        {
            get
            {
                if ((_Company_Expanses == null))
                {
                    _Company_Expanses = base.CreateObjectSet<Company_Expanses>("Company_Expanses");
                }
                return _Company_Expanses;
            }
        }
        private ObjectSet<Company_Expanses> _Company_Expanses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Owners> Owners
        {
            get
            {
                if ((_Owners == null))
                {
                    _Owners = base.CreateObjectSet<Owners>("Owners");
                }
                return _Owners;
            }
        }
        private ObjectSet<Owners> _Owners;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dispatchers> Dispatchers
        {
            get
            {
                if ((_Dispatchers == null))
                {
                    _Dispatchers = base.CreateObjectSet<Dispatchers>("Dispatchers");
                }
                return _Dispatchers;
            }
        }
        private ObjectSet<Dispatchers> _Dispatchers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Income> Income
        {
            get
            {
                if ((_Income == null))
                {
                    _Income = base.CreateObjectSet<Income>("Income");
                }
                return _Income;
            }
        }
        private ObjectSet<Income> _Income;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Company_Expanses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompany_Expanses(Company_Expanses company_Expanses)
        {
            base.AddObject("Company_Expanses", company_Expanses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Owners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOwners(Owners owners)
        {
            base.AddObject("Owners", owners);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dispatchers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDispatchers(Dispatchers dispatchers)
        {
            base.AddObject("Dispatchers", dispatchers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Income EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIncome(Income income)
        {
            base.AddObject("Income", income);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VPSS1Model", Name="Company_Expanses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company_Expanses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company_Expanses object.
        /// </summary>
        /// <param name="companyExpansesID">Initial value of the CompanyExpansesID property.</param>
        public static Company_Expanses CreateCompany_Expanses(global::System.Int32 companyExpansesID)
        {
            Company_Expanses company_Expanses = new Company_Expanses();
            company_Expanses.CompanyExpansesID = companyExpansesID;
            return company_Expanses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompanyExpansesID
        {
            get
            {
                return _CompanyExpansesID;
            }
            set
            {
                if (_CompanyExpansesID != value)
                {
                    OnCompanyExpansesIDChanging(value);
                    ReportPropertyChanging("CompanyExpansesID");
                    _CompanyExpansesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CompanyExpansesID");
                    OnCompanyExpansesIDChanged();
                }
            }
        }
        private global::System.Int32 _CompanyExpansesID;
        partial void OnCompanyExpansesIDChanging(global::System.Int32 value);
        partial void OnCompanyExpansesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expanses
        {
            get
            {
                return _Expanses;
            }
            set
            {
                OnExpansesChanging(value);
                ReportPropertyChanging("Expanses");
                _Expanses = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expanses");
                OnExpansesChanged();
            }
        }
        private global::System.String _Expanses;
        partial void OnExpansesChanging(global::System.String value);
        partial void OnExpansesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VPSS1Model", Name="Dispatchers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dispatchers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dispatchers object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Dispatchers CreateDispatchers(global::System.Int32 id)
        {
            Dispatchers dispatchers = new Dispatchers();
            dispatchers.ID = id;
            return dispatchers;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_name
        {
            get
            {
                return _Last_name;
            }
            set
            {
                OnLast_nameChanging(value);
                ReportPropertyChanging("Last_name");
                _Last_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_name");
                OnLast_nameChanged();
            }
        }
        private global::System.String _Last_name;
        partial void OnLast_nameChanging(global::System.String value);
        partial void OnLast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_name
        {
            get
            {
                return _First_name;
            }
            set
            {
                OnFirst_nameChanging(value);
                ReportPropertyChanging("First_name");
                _First_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_name");
                OnFirst_nameChanged();
            }
        }
        private global::System.String _First_name;
        partial void OnFirst_nameChanging(global::System.String value);
        partial void OnFirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SSN
        {
            get
            {
                return _SSN;
            }
            set
            {
                OnSSNChanging(value);
                ReportPropertyChanging("SSN");
                _SSN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SSN");
                OnSSNChanged();
            }
        }
        private global::System.String _SSN;
        partial void OnSSNChanging(global::System.String value);
        partial void OnSSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Hire_date
        {
            get
            {
                return _Hire_date;
            }
            set
            {
                OnHire_dateChanging(value);
                ReportPropertyChanging("Hire_date");
                _Hire_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hire_date");
                OnHire_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Hire_date;
        partial void OnHire_dateChanging(Nullable<global::System.DateTime> value);
        partial void OnHire_dateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VPSS1Model", Name="Income")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Income : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Income object.
        /// </summary>
        /// <param name="incomeID">Initial value of the IncomeID property.</param>
        public static Income CreateIncome(global::System.Int32 incomeID)
        {
            Income income = new Income();
            income.IncomeID = incomeID;
            return income;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IncomeID
        {
            get
            {
                return _IncomeID;
            }
            set
            {
                if (_IncomeID != value)
                {
                    OnIncomeIDChanging(value);
                    ReportPropertyChanging("IncomeID");
                    _IncomeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IncomeID");
                    OnIncomeIDChanged();
                }
            }
        }
        private global::System.Int32 _IncomeID;
        partial void OnIncomeIDChanging(global::System.Int32 value);
        partial void OnIncomeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IncomeDate
        {
            get
            {
                return _IncomeDate;
            }
            set
            {
                OnIncomeDateChanging(value);
                ReportPropertyChanging("IncomeDate");
                _IncomeDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncomeDate");
                OnIncomeDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _IncomeDate;
        partial void OnIncomeDateChanging(Nullable<global::System.DateTime> value);
        partial void OnIncomeDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AmountInvoiced
        {
            get
            {
                return _AmountInvoiced;
            }
            set
            {
                OnAmountInvoicedChanging(value);
                ReportPropertyChanging("AmountInvoiced");
                _AmountInvoiced = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AmountInvoiced");
                OnAmountInvoicedChanged();
            }
        }
        private Nullable<global::System.Decimal> _AmountInvoiced;
        partial void OnAmountInvoicedChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountInvoicedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FundedAmount
        {
            get
            {
                return _FundedAmount;
            }
            set
            {
                OnFundedAmountChanging(value);
                ReportPropertyChanging("FundedAmount");
                _FundedAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FundedAmount");
                OnFundedAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _FundedAmount;
        partial void OnFundedAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnFundedAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ReserveAmount
        {
            get
            {
                return _ReserveAmount;
            }
            set
            {
                OnReserveAmountChanging(value);
                ReportPropertyChanging("ReserveAmount");
                _ReserveAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReserveAmount");
                OnReserveAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _ReserveAmount;
        partial void OnReserveAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnReserveAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AdvanceFee
        {
            get
            {
                return _AdvanceFee;
            }
            set
            {
                OnAdvanceFeeChanging(value);
                ReportPropertyChanging("AdvanceFee");
                _AdvanceFee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdvanceFee");
                OnAdvanceFeeChanged();
            }
        }
        private Nullable<global::System.Decimal> _AdvanceFee;
        partial void OnAdvanceFeeChanging(Nullable<global::System.Decimal> value);
        partial void OnAdvanceFeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ChargeBacks
        {
            get
            {
                return _ChargeBacks;
            }
            set
            {
                OnChargeBacksChanging(value);
                ReportPropertyChanging("ChargeBacks");
                _ChargeBacks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChargeBacks");
                OnChargeBacksChanged();
            }
        }
        private Nullable<global::System.Decimal> _ChargeBacks;
        partial void OnChargeBacksChanging(Nullable<global::System.Decimal> value);
        partial void OnChargeBacksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VPSS1Model", Name="Owners")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Owners : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Owners object.
        /// </summary>
        /// <param name="ownerID">Initial value of the OwnerID property.</param>
        public static Owners CreateOwners(global::System.Int32 ownerID)
        {
            Owners owners = new Owners();
            owners.OwnerID = ownerID;
            return owners;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                if (_OwnerID != value)
                {
                    OnOwnerIDChanging(value);
                    ReportPropertyChanging("OwnerID");
                    _OwnerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OwnerID");
                    OnOwnerIDChanged();
                }
            }
        }
        private global::System.Int32 _OwnerID;
        partial void OnOwnerIDChanging(global::System.Int32 value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ssn_
        {
            get
            {
                return _ssn_;
            }
            set
            {
                Onssn_Changing(value);
                ReportPropertyChanging("ssn_");
                _ssn_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ssn_");
                Onssn_Changed();
            }
        }
        private global::System.String _ssn_;
        partial void Onssn_Changing(global::System.String value);
        partial void Onssn_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> fee_rate
        {
            get
            {
                return _fee_rate;
            }
            set
            {
                Onfee_rateChanging(value);
                ReportPropertyChanging("fee_rate");
                _fee_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fee_rate");
                Onfee_rateChanged();
            }
        }
        private Nullable<global::System.Single> _fee_rate;
        partial void Onfee_rateChanging(Nullable<global::System.Single> value);
        partial void Onfee_rateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> pay_rate
        {
            get
            {
                return _pay_rate;
            }
            set
            {
                Onpay_rateChanging(value);
                ReportPropertyChanging("pay_rate");
                _pay_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pay_rate");
                Onpay_rateChanged();
            }
        }
        private Nullable<global::System.Single> _pay_rate;
        partial void Onpay_rateChanging(Nullable<global::System.Single> value);
        partial void Onpay_rateChanged();

        #endregion
    
    }

    #endregion
    
}
