//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alabama.CRM {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyPairInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KeyPairInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignActiveKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineCodeField;
        
        private int OrderIdField;
        
        private int AssignContractIdField;
        
        private int PackageIdField;
        
        private System.DateTime StartDateField;
        
        private System.DateTime SaleDateField;
        
        private int KeyPairStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentVersionField;
        
        private bool IsTrialField;
        
        private int NumberOfClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SerialId {
            get {
                return this.SerialIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialIdField, value) != true)) {
                    this.SerialIdField = value;
                    this.RaisePropertyChanged("SerialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RandCode {
            get {
                return this.RandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RandCodeField, value) != true)) {
                    this.RandCodeField = value;
                    this.RaisePropertyChanged("RandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RegistKey {
            get {
                return this.RegistKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistKeyField, value) != true)) {
                    this.RegistKeyField = value;
                    this.RaisePropertyChanged("RegistKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SignActiveKey {
            get {
                return this.SignActiveKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SignActiveKeyField, value) != true)) {
                    this.SignActiveKeyField = value;
                    this.RaisePropertyChanged("SignActiveKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MachineCode {
            get {
                return this.MachineCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineCodeField, value) != true)) {
                    this.MachineCodeField = value;
                    this.RaisePropertyChanged("MachineCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int AssignContractId {
            get {
                return this.AssignContractIdField;
            }
            set {
                if ((this.AssignContractIdField.Equals(value) != true)) {
                    this.AssignContractIdField = value;
                    this.RaisePropertyChanged("AssignContractId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int PackageId {
            get {
                return this.PackageIdField;
            }
            set {
                if ((this.PackageIdField.Equals(value) != true)) {
                    this.PackageIdField = value;
                    this.RaisePropertyChanged("PackageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((this.SaleDateField.Equals(value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int KeyPairStatus {
            get {
                return this.KeyPairStatusField;
            }
            set {
                if ((this.KeyPairStatusField.Equals(value) != true)) {
                    this.KeyPairStatusField = value;
                    this.RaisePropertyChanged("KeyPairStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CurrentVersion {
            get {
                return this.CurrentVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionField, value) != true)) {
                    this.CurrentVersionField = value;
                    this.RaisePropertyChanged("CurrentVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool IsTrial {
            get {
                return this.IsTrialField;
            }
            set {
                if ((this.IsTrialField.Equals(value) != true)) {
                    this.IsTrialField = value;
                    this.RaisePropertyChanged("IsTrial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int NumberOfClient {
            get {
                return this.NumberOfClientField;
            }
            set {
                if ((this.NumberOfClientField.Equals(value) != true)) {
                    this.NumberOfClientField = value;
                    this.RaisePropertyChanged("NumberOfClient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackageInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PackageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageNameField;
        
        private int PackageDurationField;
        
        private decimal PackagePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private bool PackageUpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PackageName {
            get {
                return this.PackageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageNameField, value) != true)) {
                    this.PackageNameField = value;
                    this.RaisePropertyChanged("PackageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int PackageDuration {
            get {
                return this.PackageDurationField;
            }
            set {
                if ((this.PackageDurationField.Equals(value) != true)) {
                    this.PackageDurationField = value;
                    this.RaisePropertyChanged("PackageDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal PackagePrice {
            get {
                return this.PackagePriceField;
            }
            set {
                if ((this.PackagePriceField.Equals(value) != true)) {
                    this.PackagePriceField = value;
                    this.RaisePropertyChanged("PackagePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool PackageUpdate {
            get {
                return this.PackageUpdateField;
            }
            set {
                if ((this.PackageUpdateField.Equals(value) != true)) {
                    this.PackageUpdateField = value;
                    this.RaisePropertyChanged("PackageUpdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRM.PublicServiceSoap")]
    public interface PublicServiceSoap {
        
        // CODEGEN: Generating message contract since element name base64Sign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActivateKeyByMachineCode", ReplyAction="*")]
        Alabama.CRM.GetActivateKeyByMachineCodeResponse GetActivateKeyByMachineCode(Alabama.CRM.GetActivateKeyByMachineCodeRequest request);
        
        // CODEGEN: Generating message contract since element name base64Sign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackage", ReplyAction="*")]
        Alabama.CRM.GetPackageResponse GetPackage(Alabama.CRM.GetPackageRequest request);
        
        // CODEGEN: Generating message contract since element name base64Sign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackages", ReplyAction="*")]
        Alabama.CRM.GetPackagesResponse GetPackages(Alabama.CRM.GetPackagesRequest request);
        
        // CODEGEN: Generating message contract since element name base64Sign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeyPair", ReplyAction="*")]
        Alabama.CRM.GetKeyPairResponse GetKeyPair(Alabama.CRM.GetKeyPairRequest request);
        
        // CODEGEN: Generating message contract since element name base64Sign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActivateKeyByRegKey", ReplyAction="*")]
        Alabama.CRM.GetActivateKeyByRegKeyResponse GetActivateKeyByRegKey(Alabama.CRM.GetActivateKeyByRegKeyRequest request);
        
        // CODEGEN: Generating message contract since element name base64Sign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMachineCode", ReplyAction="*")]
        Alabama.CRM.SetMachineCodeResponse SetMachineCode(Alabama.CRM.SetMachineCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivateKeyByMachineCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivateKeyByMachineCode", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetActivateKeyByMachineCodeRequestBody Body;
        
        public GetActivateKeyByMachineCodeRequest() {
        }
        
        public GetActivateKeyByMachineCodeRequest(Alabama.CRM.GetActivateKeyByMachineCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActivateKeyByMachineCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string machineCode;
        
        public GetActivateKeyByMachineCodeRequestBody() {
        }
        
        public GetActivateKeyByMachineCodeRequestBody(string base64Sign, string productCode, string machineCode) {
            this.base64Sign = base64Sign;
            this.productCode = productCode;
            this.machineCode = machineCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivateKeyByMachineCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivateKeyByMachineCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetActivateKeyByMachineCodeResponseBody Body;
        
        public GetActivateKeyByMachineCodeResponse() {
        }
        
        public GetActivateKeyByMachineCodeResponse(Alabama.CRM.GetActivateKeyByMachineCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActivateKeyByMachineCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Alabama.CRM.KeyPairInfo GetActivateKeyByMachineCodeResult;
        
        public GetActivateKeyByMachineCodeResponseBody() {
        }
        
        public GetActivateKeyByMachineCodeResponseBody(Alabama.CRM.KeyPairInfo GetActivateKeyByMachineCodeResult) {
            this.GetActivateKeyByMachineCodeResult = GetActivateKeyByMachineCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackage", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetPackageRequestBody Body;
        
        public GetPackageRequest() {
        }
        
        public GetPackageRequest(Alabama.CRM.GetPackageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPackageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int packageId;
        
        public GetPackageRequestBody() {
        }
        
        public GetPackageRequestBody(string base64Sign, int packageId) {
            this.base64Sign = base64Sign;
            this.packageId = packageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetPackageResponseBody Body;
        
        public GetPackageResponse() {
        }
        
        public GetPackageResponse(Alabama.CRM.GetPackageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPackageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Alabama.CRM.PackageInfo GetPackageResult;
        
        public GetPackageResponseBody() {
        }
        
        public GetPackageResponseBody(Alabama.CRM.PackageInfo GetPackageResult) {
            this.GetPackageResult = GetPackageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackages", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetPackagesRequestBody Body;
        
        public GetPackagesRequest() {
        }
        
        public GetPackagesRequest(Alabama.CRM.GetPackagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPackagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productCode;
        
        public GetPackagesRequestBody() {
        }
        
        public GetPackagesRequestBody(string base64Sign, string productCode) {
            this.base64Sign = base64Sign;
            this.productCode = productCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetPackagesResponseBody Body;
        
        public GetPackagesResponse() {
        }
        
        public GetPackagesResponse(Alabama.CRM.GetPackagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPackagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Alabama.CRM.PackageInfo[] GetPackagesResult;
        
        public GetPackagesResponseBody() {
        }
        
        public GetPackagesResponseBody(Alabama.CRM.PackageInfo[] GetPackagesResult) {
            this.GetPackagesResult = GetPackagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyPairRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyPair", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetKeyPairRequestBody Body;
        
        public GetKeyPairRequest() {
        }
        
        public GetKeyPairRequest(Alabama.CRM.GetKeyPairRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyPairRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int packageId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string machineCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string version;
        
        public GetKeyPairRequestBody() {
        }
        
        public GetKeyPairRequestBody(string base64Sign, int packageId, string machineCode, string version) {
            this.base64Sign = base64Sign;
            this.packageId = packageId;
            this.machineCode = machineCode;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyPairResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyPairResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetKeyPairResponseBody Body;
        
        public GetKeyPairResponse() {
        }
        
        public GetKeyPairResponse(Alabama.CRM.GetKeyPairResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyPairResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Alabama.CRM.KeyPairInfo GetKeyPairResult;
        
        public GetKeyPairResponseBody() {
        }
        
        public GetKeyPairResponseBody(Alabama.CRM.KeyPairInfo GetKeyPairResult) {
            this.GetKeyPairResult = GetKeyPairResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivateKeyByRegKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivateKeyByRegKey", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetActivateKeyByRegKeyRequestBody Body;
        
        public GetActivateKeyByRegKeyRequest() {
        }
        
        public GetActivateKeyByRegKeyRequest(Alabama.CRM.GetActivateKeyByRegKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActivateKeyByRegKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int keyPairId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string registKey;
        
        public GetActivateKeyByRegKeyRequestBody() {
        }
        
        public GetActivateKeyByRegKeyRequestBody(string base64Sign, int keyPairId, string registKey) {
            this.base64Sign = base64Sign;
            this.keyPairId = keyPairId;
            this.registKey = registKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivateKeyByRegKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivateKeyByRegKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.GetActivateKeyByRegKeyResponseBody Body;
        
        public GetActivateKeyByRegKeyResponse() {
        }
        
        public GetActivateKeyByRegKeyResponse(Alabama.CRM.GetActivateKeyByRegKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActivateKeyByRegKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Alabama.CRM.KeyPairInfo GetActivateKeyByRegKeyResult;
        
        public GetActivateKeyByRegKeyResponseBody() {
        }
        
        public GetActivateKeyByRegKeyResponseBody(Alabama.CRM.KeyPairInfo GetActivateKeyByRegKeyResult) {
            this.GetActivateKeyByRegKeyResult = GetActivateKeyByRegKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMachineCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMachineCode", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.SetMachineCodeRequestBody Body;
        
        public SetMachineCodeRequest() {
        }
        
        public SetMachineCodeRequest(Alabama.CRM.SetMachineCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMachineCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string serialID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string randCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string machineCode;
        
        public SetMachineCodeRequestBody() {
        }
        
        public SetMachineCodeRequestBody(string base64Sign, string serialID, string randCode, string machineCode) {
            this.base64Sign = base64Sign;
            this.serialID = serialID;
            this.randCode = randCode;
            this.machineCode = machineCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMachineCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMachineCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alabama.CRM.SetMachineCodeResponseBody Body;
        
        public SetMachineCodeResponse() {
        }
        
        public SetMachineCodeResponse(Alabama.CRM.SetMachineCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMachineCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<bool> SetMachineCodeResult;
        
        public SetMachineCodeResponseBody() {
        }
        
        public SetMachineCodeResponseBody(System.Nullable<bool> SetMachineCodeResult) {
            this.SetMachineCodeResult = SetMachineCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PublicServiceSoapChannel : Alabama.CRM.PublicServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicServiceSoapClient : System.ServiceModel.ClientBase<Alabama.CRM.PublicServiceSoap>, Alabama.CRM.PublicServiceSoap {
        
        public PublicServiceSoapClient() {
        }
        
        public PublicServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alabama.CRM.GetActivateKeyByMachineCodeResponse Alabama.CRM.PublicServiceSoap.GetActivateKeyByMachineCode(Alabama.CRM.GetActivateKeyByMachineCodeRequest request) {
            return base.Channel.GetActivateKeyByMachineCode(request);
        }
        
        public Alabama.CRM.KeyPairInfo GetActivateKeyByMachineCode(string base64Sign, string productCode, string machineCode) {
            Alabama.CRM.GetActivateKeyByMachineCodeRequest inValue = new Alabama.CRM.GetActivateKeyByMachineCodeRequest();
            inValue.Body = new Alabama.CRM.GetActivateKeyByMachineCodeRequestBody();
            inValue.Body.base64Sign = base64Sign;
            inValue.Body.productCode = productCode;
            inValue.Body.machineCode = machineCode;
            Alabama.CRM.GetActivateKeyByMachineCodeResponse retVal = ((Alabama.CRM.PublicServiceSoap)(this)).GetActivateKeyByMachineCode(inValue);
            return retVal.Body.GetActivateKeyByMachineCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alabama.CRM.GetPackageResponse Alabama.CRM.PublicServiceSoap.GetPackage(Alabama.CRM.GetPackageRequest request) {
            return base.Channel.GetPackage(request);
        }
        
        public Alabama.CRM.PackageInfo GetPackage(string base64Sign, int packageId) {
            Alabama.CRM.GetPackageRequest inValue = new Alabama.CRM.GetPackageRequest();
            inValue.Body = new Alabama.CRM.GetPackageRequestBody();
            inValue.Body.base64Sign = base64Sign;
            inValue.Body.packageId = packageId;
            Alabama.CRM.GetPackageResponse retVal = ((Alabama.CRM.PublicServiceSoap)(this)).GetPackage(inValue);
            return retVal.Body.GetPackageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alabama.CRM.GetPackagesResponse Alabama.CRM.PublicServiceSoap.GetPackages(Alabama.CRM.GetPackagesRequest request) {
            return base.Channel.GetPackages(request);
        }
        
        public Alabama.CRM.PackageInfo[] GetPackages(string base64Sign, string productCode) {
            Alabama.CRM.GetPackagesRequest inValue = new Alabama.CRM.GetPackagesRequest();
            inValue.Body = new Alabama.CRM.GetPackagesRequestBody();
            inValue.Body.base64Sign = base64Sign;
            inValue.Body.productCode = productCode;
            Alabama.CRM.GetPackagesResponse retVal = ((Alabama.CRM.PublicServiceSoap)(this)).GetPackages(inValue);
            return retVal.Body.GetPackagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alabama.CRM.GetKeyPairResponse Alabama.CRM.PublicServiceSoap.GetKeyPair(Alabama.CRM.GetKeyPairRequest request) {
            return base.Channel.GetKeyPair(request);
        }
        
        public Alabama.CRM.KeyPairInfo GetKeyPair(string base64Sign, int packageId, string machineCode, string version) {
            Alabama.CRM.GetKeyPairRequest inValue = new Alabama.CRM.GetKeyPairRequest();
            inValue.Body = new Alabama.CRM.GetKeyPairRequestBody();
            inValue.Body.base64Sign = base64Sign;
            inValue.Body.packageId = packageId;
            inValue.Body.machineCode = machineCode;
            inValue.Body.version = version;
            Alabama.CRM.GetKeyPairResponse retVal = ((Alabama.CRM.PublicServiceSoap)(this)).GetKeyPair(inValue);
            return retVal.Body.GetKeyPairResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alabama.CRM.GetActivateKeyByRegKeyResponse Alabama.CRM.PublicServiceSoap.GetActivateKeyByRegKey(Alabama.CRM.GetActivateKeyByRegKeyRequest request) {
            return base.Channel.GetActivateKeyByRegKey(request);
        }
        
        public Alabama.CRM.KeyPairInfo GetActivateKeyByRegKey(string base64Sign, int keyPairId, string registKey) {
            Alabama.CRM.GetActivateKeyByRegKeyRequest inValue = new Alabama.CRM.GetActivateKeyByRegKeyRequest();
            inValue.Body = new Alabama.CRM.GetActivateKeyByRegKeyRequestBody();
            inValue.Body.base64Sign = base64Sign;
            inValue.Body.keyPairId = keyPairId;
            inValue.Body.registKey = registKey;
            Alabama.CRM.GetActivateKeyByRegKeyResponse retVal = ((Alabama.CRM.PublicServiceSoap)(this)).GetActivateKeyByRegKey(inValue);
            return retVal.Body.GetActivateKeyByRegKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alabama.CRM.SetMachineCodeResponse Alabama.CRM.PublicServiceSoap.SetMachineCode(Alabama.CRM.SetMachineCodeRequest request) {
            return base.Channel.SetMachineCode(request);
        }
        
        public System.Nullable<bool> SetMachineCode(string base64Sign, string serialID, string randCode, string machineCode) {
            Alabama.CRM.SetMachineCodeRequest inValue = new Alabama.CRM.SetMachineCodeRequest();
            inValue.Body = new Alabama.CRM.SetMachineCodeRequestBody();
            inValue.Body.base64Sign = base64Sign;
            inValue.Body.serialID = serialID;
            inValue.Body.randCode = randCode;
            inValue.Body.machineCode = machineCode;
            Alabama.CRM.SetMachineCodeResponse retVal = ((Alabama.CRM.PublicServiceSoap)(this)).SetMachineCode(inValue);
            return retVal.Body.SetMachineCodeResult;
        }
    }
}
