//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Alabama
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VPSS1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VPSS1Entities object using the connection string found in the 'VPSS1Entities' section of the application configuration file.
        /// </summary>
        public VPSS1Entities() : base("name=VPSS1Entities", "VPSS1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VPSS1Entities object.
        /// </summary>
        public VPSS1Entities(string connectionString) : base(connectionString, "VPSS1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VPSS1Entities object.
        /// </summary>
        public VPSS1Entities(EntityConnection connection) : base(connection, "VPSS1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company_Expanses> Company_Expanses
        {
            get
            {
                if ((_Company_Expanses == null))
                {
                    _Company_Expanses = base.CreateObjectSet<Company_Expanses>("Company_Expanses");
                }
                return _Company_Expanses;
            }
        }
        private ObjectSet<Company_Expanses> _Company_Expanses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Owners> Owners
        {
            get
            {
                if ((_Owners == null))
                {
                    _Owners = base.CreateObjectSet<Owners>("Owners");
                }
                return _Owners;
            }
        }
        private ObjectSet<Owners> _Owners;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Company_Expanses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompany_Expanses(Company_Expanses company_Expanses)
        {
            base.AddObject("Company_Expanses", company_Expanses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Owners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOwners(Owners owners)
        {
            base.AddObject("Owners", owners);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VPSS1Model", Name="Company_Expanses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company_Expanses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company_Expanses object.
        /// </summary>
        /// <param name="companyExpansesID">Initial value of the CompanyExpansesID property.</param>
        public static Company_Expanses CreateCompany_Expanses(global::System.Int32 companyExpansesID)
        {
            Company_Expanses company_Expanses = new Company_Expanses();
            company_Expanses.CompanyExpansesID = companyExpansesID;
            return company_Expanses;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompanyExpansesID
        {
            get
            {
                return _CompanyExpansesID;
            }
            set
            {
                if (_CompanyExpansesID != value)
                {
                    OnCompanyExpansesIDChanging(value);
                    ReportPropertyChanging("CompanyExpansesID");
                    _CompanyExpansesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CompanyExpansesID");
                    OnCompanyExpansesIDChanged();
                }
            }
        }
        private global::System.Int32 _CompanyExpansesID;
        partial void OnCompanyExpansesIDChanging(global::System.Int32 value);
        partial void OnCompanyExpansesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expanses
        {
            get
            {
                return _Expanses;
            }
            set
            {
                OnExpansesChanging(value);
                ReportPropertyChanging("Expanses");
                _Expanses = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expanses");
                OnExpansesChanged();
            }
        }
        private global::System.String _Expanses;
        partial void OnExpansesChanging(global::System.String value);
        partial void OnExpansesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VPSS1Model", Name="Owners")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Owners : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Owners object.
        /// </summary>
        /// <param name="ownerID">Initial value of the OwnerID property.</param>
        public static Owners CreateOwners(global::System.Int32 ownerID)
        {
            Owners owners = new Owners();
            owners.OwnerID = ownerID;
            return owners;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                if (_OwnerID != value)
                {
                    OnOwnerIDChanging(value);
                    ReportPropertyChanging("OwnerID");
                    _OwnerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OwnerID");
                    OnOwnerIDChanged();
                }
            }
        }
        private global::System.Int32 _OwnerID;
        partial void OnOwnerIDChanging(global::System.Int32 value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ssn_
        {
            get
            {
                return _ssn_;
            }
            set
            {
                Onssn_Changing(value);
                ReportPropertyChanging("ssn_");
                _ssn_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ssn_");
                Onssn_Changed();
            }
        }
        private global::System.String _ssn_;
        partial void Onssn_Changing(global::System.String value);
        partial void Onssn_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> fee_rate
        {
            get
            {
                return _fee_rate;
            }
            set
            {
                Onfee_rateChanging(value);
                ReportPropertyChanging("fee_rate");
                _fee_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fee_rate");
                Onfee_rateChanged();
            }
        }
        private Nullable<global::System.Single> _fee_rate;
        partial void Onfee_rateChanging(Nullable<global::System.Single> value);
        partial void Onfee_rateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> pay_rate
        {
            get
            {
                return _pay_rate;
            }
            set
            {
                Onpay_rateChanging(value);
                ReportPropertyChanging("pay_rate");
                _pay_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pay_rate");
                Onpay_rateChanged();
            }
        }
        private Nullable<global::System.Single> _pay_rate;
        partial void Onpay_rateChanging(Nullable<global::System.Single> value);
        partial void Onpay_rateChanged();

        #endregion

    
    }

    #endregion

    
}
